### ISSUE TITLE
Finding wrong copy of heroes in RoE Dungeons and Devils campaign Map #3

### ISSUE THREAD

**Issue by WolffHobbitStomper** [suurjaak/h3sed#10] opened 2024-06-13 05:04 UTC
Save files created at the start of Stedwick's Fall RoE campaign map (Final Map #3).
For this campaign each of the first two maps can carry over a party of 8 heroes.
So at the start of map 3 the save may contain 2x8 carryover heroes (there appear near the start of the save).

When loading the saves in h3sed 
1. it's finding the copy of the imported heroes complete with artifacts and creatures from the previous map(s) editing these has no effect in game.
2. For a carryover of 8 heroes it finds heroes 2..8 but not the first in the party.
3. For a carryover of single hero maps all heroes except the carryover hero are available. 

Looking in the saves there appear to be two carryover parties at the start of the file and then the active heroes later on. 

[test4.zip](https://github.com/user-attachments/files/15813811/test4.zip)

**Comment by WolffHobbitStomper** [comment] 2024-06-13 08:42
After a bit more investigation I've found the reason.
in plugins/heroes/__init__.py Line 922
        pos = 10000 # Hero structs are more to the end of the file

Increasing this (in this case to ~19000) gets past the carry over heroes.

**Comment by suurjaak** [comment] 2024-06-14 07:33
Those savegames do have the Shadow of Death version bytes, so it cannot but detect them as such. 

Can you try this version: 
[h3sed_2.4.dev14-src.zip](https://github.com/user-attachments/files/15833138/h3sed_2.4.dev14-src.zip)

**Comment by WolffHobbitStomper** [comment] 2024-06-14 08:35
I did a test to find the size of the smallest possible map. Constructed a "Small" map with a bit of ground and two opposing heroes with nothing else.
For this the offset in the save to the name of the first hero in the hero list is 0x7C20 (Single Map) or 0x7C80 (1 Map Campaign).
So I would suggest a safe offset to start searching for the hero list is 30000.
I've attached the test map/campaign this was created as RoE format but my saves are detected as SoD format by h3sed!

[SmallMap.zip](https://github.com/user-attachments/files/15828741/SmallMap.zip)

**Comment by WolffHobbitStomper** [comment] 2024-06-14 08:39
After sorting out my missing python step-template library, the 2.4 dev14 seems to be all correct.
Inventory correct in RoE and AB. Saves with many carry over heroes all showing up correctly.

**Comment by suurjaak** [comment] 2024-06-14 08:39
Your last comment is a duplicate of yesterday's?

**Comment by WolffHobbitStomper** [comment] 2024-06-14 08:43
Not sure what happened there, I may have failed to refresh the web page before posting.

After sorting out my missing python step-template library, the 2.4 dev14 seems to be all correct.
Inventory correct in RoE and AB. Saves with many carry over heroes all showing up correctly.

**Comment by suurjaak** [comment] 2024-06-14 19:10
Released version 2.4 with these and other fixes. 

Thank you, you've been of most excellent help.

**Closed by suurjaak** 2024-06-14 19:10 UTC
